# Generated by Django 4.0 on 2022-01-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inch',
            new_name='TireInch',
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('tire_inch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_inch', to='stock.tireinch')),
            ],
        ),
    ]
