# Generated by Django 4.0 on 2022-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_inch_tireinch_tire'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
