# Generated by Django 4.0 on 2022-04-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_tire_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('spec',)},
        ),
        migrations.AlterModelOptions(
            name='tireinch',
            options={'ordering': ['inch']},
        ),
        migrations.AlterField(
            model_name='tire',
            name='quantity',
            field=models.CharField(choices=[('null', 'null'), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default='null', max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.IntegerField()),
                ('after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tire_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_spec', to='stock.tire')),
            ],
        ),
    ]
