# Generated by Django 3.2.5 on 2021-11-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_name_sort_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
