# Generated by Django 3.2.5 on 2021-11-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='sorts',
        ),
    ]
