# Generated by Django 3.2.5 on 2021-11-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_detail_sorts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='sort',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
