# Generated by Django 3.2.5 on 2021-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.TextField(blank=True),
        ),
    ]
