# Generated by Django 3.2.5 on 2021-07-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='terms',
        ),
    ]
